name: Azure Functions Python app on Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Set up Python version'
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Use the Python version compatible with Azure Functions

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'scraper-premium'
          package: '.'
